closed_loop
figure(2)
subplot(2,2,1)
pzmap(T(1))
title('Position')
subplot(2,2,2)
step(T(1))
title('Position Step Response')
subplot(2,2,3)
pzmap(T(2))
title('Angle')
subplot(2,2,4)
step(T(2))
title('Angle Step Response')